### ISSUE TITLE
moderncvheadiii.sty compilation error

### ISSUE THREAD

**Issue by phuidn** [xdanaux/moderncv#98]
Runnig `pdflatex template.tex` with `\moderncvstyle{classic}` changed to `\moderncvstyle{banking}`, I get an error:
```
(/opt/local/share/texmf-local/tex/latex/moderncv/moderncvheadiii.sty
Runaway argument?
{\setlength {\makeheaddetailswidth }{0.8\textwidth }\hfil \parbox {\makeheaddet
ailswidth \ETC.
! Paragraph ended before \@initializecommand was complete.
<to be read again> 
                   \par 
l.86 
```
As far as I can tell this is caused by commit `a4a2062ac9e5a661a629ff05de2822500f1b69f1` (when I revert that commit's change to that file, it compiles), but I'm not sure why. My latex is a little rusty to say the least.

**Comment by phuidn** [comment]
A little more digging: the change that caused the error seems to be a newline added on line 86 of `moderncvheadiii.sty` in commit `a4a2062a`
